application: pubcron
version: live
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: jinja2
  version: latest

builtins:
- deferred: on
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /send
  script: send.app
  login: admin

- url: /feedback
  script: feedback.app
  secure: optional

- url: /.*
  script: pubcron.app
