application: pubcron
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /send
  script: send.py
  login: admin

- url: /.*
  script: pubcron.py
