application: pubcron
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /send
  script: pubcron_send.py
  login: admin

- url: /(update|query.html?)
  script: pubcron_my_query.py
  login: required

- url: /feedback
  script: pubcron_feedback.py
  secure: optional

- url: /.*
  script: pubcron_nologin.py

builtins:
- remote_api: on
