application: pubcron
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /send
  script: send.py
  login: admin

- url: /(update|mailupdate|query.html?)
  script: pubcron.py
  login: required

- url: /.*
  script: nologin.py

builtins:
- remote_api: on
